// AUTO-GENERATED by scripts/generate-maps.mjs — do not edit by hand.
// Projection parameters for the dotted maps in /public/maps (Natural Earth via world-atlas, public domain).
export const WORLD_MAP = {"bounds":[-130,160,-45,72],"scaleX":4,"scaleY":4,"width":1160,"height":468} as const;
export const INDIA_MAP = {"bounds":[66,98,6,37],"scaleX":18.54367709133575,"scaleY":20,"width":593.4,"height":620} as const;
