// Generates the dotted-map SVG paths used by the hero, repatriation and network visuals.
// Source: Natural Earth via `world-atlas` (public domain). Run: `node scripts/generate-maps.mjs`
// Output is committed so the site ships zero map tiles and zero geo libraries.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoContains } from "d3-geo";

const r = (n) => Math.round(n * 10) / 10;

function dots({ geo, bounds, step, scaleX, scaleY, highlight }) {
  const [lonMin, lonMax, latMin, latMax] = bounds;
  const base = [];
  const hi = [];
  for (let lat = latMax; lat >= latMin; lat -= step) {
    for (let lon = lonMin; lon <= lonMax; lon += step) {
      const p = [lon, lat];
      const x = r((lon - lonMin) * scaleX);
      const y = r((latMax - lat) * scaleY);
      if (highlight && geoContains(highlight, p)) hi.push([x, y]);
      else if (geoContains(geo, p)) base.push([x, y]);
    }
  }
  const toPath = (pts) => pts.map(([x, y]) => `M${x} ${y}h0`).join("");
  return {
    width: r((lonMax - lonMin) * scaleX),
    height: r((latMax - latMin) * scaleY),
    base: toPath(base),
    highlight: toPath(hi),
    count: base.length + hi.length,
  };
}

// World (repatriation / network): equirectangular, cropped to inhabited latitudes.
const land110 = feature(
  JSON.parse(readFileSync("node_modules/world-atlas/land-110m.json", "utf8")),
  JSON.parse(readFileSync("node_modules/world-atlas/land-110m.json", "utf8")).objects.land,
);

const WORLD = { bounds: [-130, 160, -45, 72], step: 2.2, scaleX: 4, scaleY: 4 };
// No country is highlighted: political boundaries are deliberately not depicted (official Indian boundary
// depiction differs from Natural Earth defaults). Only landmass is drawn.
const world = dots({ geo: land110, ...WORLD });

// India region (hero / city pages): cos(latitude) corrected so the subcontinent keeps its shape.
const land50 = feature(
  JSON.parse(readFileSync("node_modules/world-atlas/land-50m.json", "utf8")),
  JSON.parse(readFileSync("node_modules/world-atlas/land-50m.json", "utf8")).objects.land,
);
const k = Math.cos((22 * Math.PI) / 180);
const INDIA = { bounds: [66, 98, 6, 37], step: 0.55, scaleX: 20 * k, scaleY: 20 };
const indiaMap = dots({ geo: land50, ...INDIA });

// Dots ship as cacheable static SVGs; only the projection parameters go into the JS bundle.
const THEMES = {
  light: { base: "#BCCAD6" },
  dark: { base: "#2A4661" },
};
function writeSvg(name, m, dotSize) {
  for (const [theme, c] of Object.entries(THEMES)) {
    const svg =
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${m.width} ${m.height}" fill="none" stroke-linecap="round" stroke-width="${dotSize}">` +
      `<path stroke="${c.base}" d="${m.base}"/></svg>`;
    writeFileSync(`public/maps/${name}-${theme}.svg`, svg);
    console.log(name, theme, svg.length, "bytes");
  }
}
mkdirSync("public/maps", { recursive: true });
writeSvg("world", world, 4.4);
writeSvg("india", indiaMap, 5.6);

const meta = (cfg, m) => ({ bounds: cfg.bounds, scaleX: cfg.scaleX, scaleY: cfg.scaleY, width: m.width, height: m.height });
const out = `// AUTO-GENERATED by scripts/generate-maps.mjs — do not edit by hand.
// Projection parameters for the dotted maps in /public/maps (Natural Earth via world-atlas, public domain).
export const WORLD_MAP = ${JSON.stringify(meta(WORLD, world))} as const;
export const INDIA_MAP = ${JSON.stringify(meta(INDIA, indiaMap))} as const;
`;
writeFileSync("src/lib/geo/map-data.ts", out);
console.log("world dots", world.count, "india dots", indiaMap.count);
